### ISSUE TITLE
Run `yamllint` with `pre-commit`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2526]
I guess we should add yamllint to pre-commit config

This should be fairly simple given yamllint repo contains a [pre-commit config](https://github.com/adrienverge/yamllint/blob/master/.pre-commit-hooks.yaml)
```yaml
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
```

_Originally posted by @touilleMan in https://github.com/Scille/parsec-cloud/pull/2499#discussion_r907797437_
