### ISSUE TITLE
`libparsec` and `libparsec_python` are creating artifact with the same name

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2637]
rust crates `oxidation/libparsec` and `oxidation/libparsec_python` are creating artifact with the same name because of `libparsec_python` being configured as follow

```toml
[lib]
name = "libparsec"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]
```

I we were to use the lib `libparsec` for something other than binding to rust, right now we would be using the lib generated by `libparsec_python`
