### ISSUE TITLE
[🐛 | Bug]: `parsec-backend` can't start because of `getpwuid(): uid not found 1234`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5370]
### Version

2.16

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

The docker container is configured to execute the command with the arbitrary user with id `1234:1234`

https://github.com/Scille/parsec-cloud/blob/9cdaec0075dea51108c648dc86dc843a4163a5fa/packaging/server/server.dockerfile#L36

This raise an `KeyError` exception in the container because the python code will use `getpwuid` with the current user id that isn't a real user. 

#### Workaround

Overwrite the user value, for example in a docker compose file:

```yaml
services:
  parsec-backend:
    image: Scille/parsec-server:2.16
    user: 0:0 # Line added to use a well know user inside the container (i.e. `root`)
```
