### ISSUE TITLE
Provide attestation for GitHub action's artifact

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#7408]
GitHub provide a public Beta to sign & verify artifacts using Sigstore:

https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/

1. Add the required permission:
   ```yaml
   permissions:
     id-token: write
     attestations: write
     contents: read
   ```

2. Use the action `attest-build-provenance`

   ```yaml
   - name: Attest Build Provenance
     uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
     with:
       subject-path: "bin/my-artifact.tar.gz"
   ```
