### ISSUE TITLE
Use taplo to format toml files

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#7741]
`taplo` is a tool used to format toml files.

It's included in the vscode extension [`tamasfe.even-better-toml`](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml)

Currently it doesn't have a pre-commit hook, but that worked on tamasfe/taplo#535

But following the promising PR tamasfe/taplo#549

we could use the hook:

```yaml
  - repo: https://github.com/redeboer/taplo-pre-commit
    rev: v0.9.1rc1
    hooks:
      - id: taplo
```
